<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class AppLog extends Model
{
 
  /**
   * The table associated with the model.
   *
   * @var string
   */
  protected $table = 'app_logs';

  /**
   * The primary key associated with the table.
   *
   * @var string
   */
  protected $primaryKey = 'id';
  const CREATED_AT = 'created_at';
  const UPDATED_AT = 'updated_at';

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
      'title', 'event', 'log_data', 'request', 'description', 'response'
  ];

  /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
  protected $hidden = [

  ];

  /**
   * Hash the password before saving into database
   * API save the token for the user
   */
  protected static function boot()
  {
      parent::boot(); // TODO: Change the autogenerated stub
  }

   public static $createRules = [
      'title' => 'required',
  ];

}
